### ISSUE TITLE
a simple decision that change Tag between GER and GEP

### ISSUE THREAD

**Issue by fgf1011** [JihadiJackass/Formable-Nations-Reworked-EU4#11]
Hello, I am the person who asked about the GER tag stuff. I wrote a simple decision to change tag between them. Here is the code:
`country_decisions = {

	change_tag_GER_to_GEP = {
		major = yes
		potential = {
			normal_or_historical_nations = yes
			was_never_end_game_tag_trigger = yes
			NOT = { exists = GEP }
			culture_group = germanic
			ai = no
			tag = GER
			}
			
		allow = {
			ai = no
			#copy form the vanilla form german
			adm_tech = 15 #original 20
			is_free_or_tributary_trigger = yes
			is_nomad = no
			is_at_war = no
			is_emperor = no
			owns_core_province = 50	# Berlin
			owns_core_province = 57	# Brunswick
			owns_core_province = 65	# M黱chen
			OR = {
				owns_core_province = 1868 # Augsburg
				owns_core_province = 70 # Wurttemberg
			}
			OR = {
				owns_core_province = 67	# N黵nberg
				owns_core_province = 1876 # Frankfurt
			}
			OR = {
				owns_core_province = 1762 # Niederhessen
				owns_core_province = 85	# K鰈n
			}
			OR = {
				owns_core_province = 41	# K鰊igsberg
				owns_core_province = 75	# Strassburg
			}
			OR = {
				owns_core_province = 44	# Hamburg
				owns_core_province = 45	# Lubeck
			}
			OR = {
				owns_core_province = 61	# Dresden
				owns_core_province = 63	# Th黵ingen
			}
			num_of_owned_provinces_with = {
				is_core = ROOT
				OR = {
					region = north_german_region
					region = south_german_region
				}
				value = 60 #original 50
			}
		}		
		effect = {
			change_tag = GEP
			restore_country_name_effect = yes
			}
		ai_will_do = {
			factor = 0
		}
	}
	
	change_tag_GEP_to_GER = {
		major = yes
		potential = {
			normal_or_historical_nations = yes
			was_never_end_game_tag_trigger = yes
			NOT = { exists = GER }
			culture_group = germanic
			ai = no
			tag = GEP
			}
			
		allow = {
			ai = no
			#copy form the vanilla form german
			adm_tech = 15 #original 20
			is_free_or_tributary_trigger = yes
			is_nomad = no
			is_at_war = no
			is_emperor = no
			owns_core_province = 50	# Berlin
			owns_core_province = 57	# Brunswick
			owns_core_province = 65	# M黱chen
			OR = {
				owns_core_province = 1868 # Augsburg
				owns_core_province = 70 # Wurttemberg
			}
			OR = {
				owns_core_province = 67	# N黵nberg
				owns_core_province = 1876 # Frankfurt
			}
			OR = {
				owns_core_province = 1762 # Niederhessen
				owns_core_province = 85	# K鰈n
			}
			OR = {
				owns_core_province = 41	# K鰊igsberg
				owns_core_province = 75	# Strassburg
			}
			OR = {
				owns_core_province = 44	# Hamburg
				owns_core_province = 45	# Lubeck
			}
			OR = {
				owns_core_province = 61	# Dresden
				owns_core_province = 63	# Th黵ingen
			}
			num_of_owned_provinces_with = {
				is_core = ROOT
				OR = {
					region = north_german_region
					region = south_german_region
				}
				value = 60 #original 50
			}
		}		
		effect = {
			change_tag = GER
			restore_country_name_effect = yes
			}
		ai_will_do = {
			factor = 0
		}
	}
}`

**Comment by noah1gamble** [comment]
> Hello, I am the person who asked about the GER tag stuff. I wrote a simple decision to change tag between them. Here is the code: `country_decisions = {
> 
> ```
> change_tag_GER_to_GEP = {
> 	major = yes
> 	potential = {
> 		normal_or_historical_nations = yes
> 		was_never_end_game_tag_trigger = yes
> 		NOT = { exists = GEP }
> 		culture_group = germanic
> 		ai = no
> 		tag = GER
> 		}
> 		
> 	allow = {
> 		ai = no
> 		#copy form the vanilla form german
> 		adm_tech = 15 #original 20
> 		is_free_or_tributary_trigger = yes
> 		is_nomad = no
> 		is_at_war = no
> 		is_emperor = no
> 		owns_core_province = 50	# Berlin
> 		owns_core_province = 57	# Brunswick
> 		owns_core_province = 65	# M黱chen
> 		OR = {
> 			owns_core_province = 1868 # Augsburg
> 			owns_core_province = 70 # Wurttemberg
> 		}
> 		OR = {
> 			owns_core_province = 67	# N黵nberg
> 			owns_core_province = 1876 # Frankfurt
> 		}
> 		OR = {
> 			owns_core_province = 1762 # Niederhessen
> 			owns_core_province = 85	# K鰈n
> 		}
> 		OR = {
> 			owns_core_province = 41	# K鰊igsberg
> 			owns_core_province = 75	# Strassburg
> 		}
> 		OR = {
> 			owns_core_province = 44	# Hamburg
> 			owns_core_province = 45	# Lubeck
> 		}
> 		OR = {
> 			owns_core_province = 61	# Dresden
> 			owns_core_province = 63	# Th黵ingen
> 		}
> 		num_of_owned_provinces_with = {
> 			is_core = ROOT
> 			OR = {
> 				region = north_german_region
> 				region = south_german_region
> 			}
> 			value = 60 #original 50
> 		}
> 	}		
> 	effect = {
> 		change_tag = GEP
> 		restore_country_name_effect = yes
> 		}
> 	ai_will_do = {
> 		factor = 0
> 	}
> }
> 
> change_tag_GEP_to_GER = {
> 	major = yes
> 	potential = {
> 		normal_or_historical_nations = yes
> 		was_never_end_game_tag_trigger = yes
> 		NOT = { exists = GER }
> 		culture_group = germanic
> 		ai = no
> 		tag = GEP
> 		}
> 		
> 	allow = {
> 		ai = no
> 		#copy form the vanilla form german
> 		adm_tech = 15 #original 20
> 		is_free_or_tributary_trigger = yes
> 		is_nomad = no
> 		is_at_war = no
> 		is_emperor = no
> 		owns_core_province = 50	# Berlin
> 		owns_core_province = 57	# Brunswick
> 		owns_core_province = 65	# M黱chen
> 		OR = {
> 			owns_core_province = 1868 # Augsburg
> 			owns_core_province = 70 # Wurttemberg
> 		}
> 		OR = {
> 			owns_core_province = 67	# N黵nberg
> 			owns_core_province = 1876 # Frankfurt
> 		}
> 		OR = {
> 			owns_core_province = 1762 # Niederhessen
> 			owns_core_province = 85	# K鰈n
> 		}
> 		OR = {
> 			owns_core_province = 41	# K鰊igsberg
> 			owns_core_province = 75	# Strassburg
> 		}
> 		OR = {
> 			owns_core_province = 44	# Hamburg
> 			owns_core_province = 45	# Lubeck
> 		}
> 		OR = {
> 			owns_core_province = 61	# Dresden
> 			owns_core_province = 63	# Th黵ingen
> 		}
> 		num_of_owned_provinces_with = {
> 			is_core = ROOT
> 			OR = {
> 				region = north_german_region
> 				region = south_german_region
> 			}
> 			value = 60 #original 50
> 		}
> 	}		
> 	effect = {
> 		change_tag = GER
> 		restore_country_name_effect = yes
> 		}
> 	ai_will_do = {
> 		factor = 0
> 	}
> }
> ```
> 
> }`

I actually worked on a better alternative if you don't mind (APOLOGIES FOR YOU TYPING THAT OUT) which is going to add three new German formables, Germany (modern germany) [German Kingdom](https://en.wikipedia.org/wiki/Kingdom_of_Germany), and German Empire

Thoughts?

**Comment by JihadiJackass** [comment]
German rework planned, which will handle this.
